osx_image: xcode7.3
language: objective-c
cache:
  - cocoapods
before_install:
  - gem install cocoapods
install:
  - cd ImagePickerSheetController && pod install && cd ..
xcode_workspace: ImagePickerSheetController.xcworkspace
xcode_scheme: ImagePickerSheetController
xcode_sdk: iphonesimulator
